_RECV_FLG BIT 00h
_SEND_FLG BIT 01h
_RECV_BUF DATA 030h

ORG 0000h
_RESET:
    LJMP _INIT
ORG 0100h
ORG 0023h
_INT_SERIAL:
    JB TI, _INT_SERIAL_TI
_INT_SERIAL_RI:
    MOV _RECV_BUF, SBUF
    CLR RI
    SETB _RECV_FLG
    RETI
_INT_SERIAL_TI:
    CLR TI
    SETB _SEND_FLG
    RETI
_INIT:
    SETB ES
    SETB EA
    CLR _RECV_FLG
    CLR _SEND_FLG
    MOV _RECV_BUF, #0d
    MOV SCON, #01010000b
    ANL TMOD, #00101111b
    ORL TMOD, #00100000b
    MOV TL1, #0FDh
    MOV TH1, #0FDh
    ANL PCON, #01111111b
    CLR TF1
    SETB TR1
_LOOP:
    JNB _RECV_FLG,_LOOP10
    CLR _RECV_FLG
    MOV R7, #0d
    SETB _SEND_FLG
_LOOP10:
    JNB _SEND_FLG, _LOOP
    CLR _SEND_FLG
    MOV A, R7
    INC R7
    MOV DPTR, #_MESSAGE
    MOVC A, @A+DPTR
    JZ _LOOP
    MOV SBUF, A
    LJMP _LOOP
_MESSAGE:
    DB 'WITAJ', 013d, 010d, 0d
END
